#!/usr/bin/env python
"""
Crossword Builder CLI entry point.
"""
import sys
import traceback

try:
    from src.cli import cli
    cli()
except Exception as e:
    traceback.print_exc(file=sys.stderr)
    sys.exit(1)
